### ISSUE TITLE
Dodawanie i przeglądanie zadań

### ISSUE THREAD

**Issue by karczewskip** [dontMakeMeQQ/Test#1]
Wprowadzenie:

Pierwsze issue ma za zadanie Cię rozruszać w kontekście Htmla i Javascriptu. Chciałbym abyś dodał możliwość dodawania zadań. Nie będzie to nic zaawansowanego. Na razie chciałbym aby przy uruchamianiu strony widniał jakiś input do wprowadzania tekstu obok niego przycisk do dodawania zadania, które znajduje się w inpucie do listy pod spodem.

Zadanie:

1. Dodaj input z wprowadzaniem tekstu.
2. Dodaj przycisk zatwierdzający zadanie.
3. Dodaj listę zadań pod spodem. Ma ona mieć tytuł wytłuszczonym drukiem a pod spodem mają pokazywać się zadania.
4. Dodaj event do przycisku onClick (https://www.w3schools.com/jsref/event_onclick.asp) ma on za zadanie po pierwsze czyścić pole input a po drugie dodawać zadania do listy.
5. Dodać Validator(tekst obok przycisku o czerwonym kolorze, kóry tłumaczy co się dzieje). Ma on się pojawiać po próbie dodania pustego zadania, a po udanej próbie znikać. Na początku ma nie byc widoczny. Fajnie jakbyś użył atrybutu hidden (https://www.w3schools.com/tags/att_global_hidden.asp, https://www.w3schools.com/jsref/met_element_setattribute.asp, https://www.w3schools.com/jsref/met_element_removeattribute.asp).

Testy akceptacyjne:
1. Wchodzę na stronę. Wpisuję zadanie w inpucie. Klikam przycisk. Zadanie pojawia się na liście. Input robi się pusty. Dodawanie powtarzam kilka razy.

2. Próbuję dodać zadanie bez podania jego tytułu. Pojawia mi się wiadomość(Validator), ze nie można dodać pustego zadania. Lista pozostaje bez zmian. Następnie wpisuję coś w input i klikam przycisk. Zadanie pojaiwa się na liście. Input znowu robi się pusty.

**Comment by dontMakeMeQQ** [comment]
@karczewskip Gotowe.

**Comment by karczewskip** [comment]
Mam pare uwag do twojego rozwiązania:

Funkcjonalne:
- Po wpisaniu spacji, tabulatorów i innych tego typu znaków mogę dodać puste zadanie. Chciałbym aby zadanie miało choć jeden zank inny niż pusty.
- Chciałbym abyś poprawił tekst na przycisku. Wiem, że to nie jest jakoś mega wazne ale wolałbym abyśmy byli konsekwentni.

Techniczne:
- Generujesz id nowo podanych tasków jak ich tekst. Jest to złe zachowanie jeżeli chodzi o specyfikacje htmla (spacje w przykładowym zadaniu: "Kupie mleko"). Tu masz dyskusje na ten temat: https://stackoverflow.com/questions/70579/what-are-valid-values-for-the-id-attribute-in-html . Chciałbym aby każde z kolejnych zadań miało id w formacie: task<nr zadania> np task1.
- Fajnie, że zrobiłeś funkcję która działa. Chciałbym jednak aby jej nazwa była czytelna. Będę się o to czepiał. Nazwij tak żeby mówiła co w rzeczywistości robi. Np. addNewTask(). Do tego w środku funkcji masz zamienne (ul, text, li) które w ogóle nic nie mówią. Nazwij je w sposób bardizej czytelny np: var addingTask = document.getElementById("text").value; i z nich korzystaj. Tam też jest problem, że piszesz wielokrotnie to samo tzn ta część: document.getElementById("text") powtarza się w kilku miejscach. W tym momencie nie jest to jakoś bolące ale wyobraź sobie, że w każdym miejscu będziesz chciał tak robić. a potem id elementu się zmienia. Zrobisz sobie dużo roboty.

czy to nie jest bardziej czytelne?

function addNewTask() {
	
    var newTaskInput = document.getElementById("text")
	var newTask = noweZadanieInput.value;
	var validationMessage = document.getElementById('QQQ');
    
    if (newTask == '') {
		
        validationMessage.removeAttribute('hidden');

    } else {
		
		var taskList = document.getElementById("list");
		var newTaskElement = document.createElement("li");
        newTaskElement.setAttribute('id', newTask);
        newTaskElement.appendChild(document.createTextNode(newTask));
        taskList.appendChild(newTaskElement);
        newTaskInput.value = "";

        validationMessage.setAttribute('hidden', true);
    }
}
- Zmień id dla elementów htmla. Przykładem jest QQQ, który nic mi nie mówi.

**Comment by karczewskip** [comment]
Dalej nie zmieniło się pare rzeczy po moich uwagach. 

1. Id tasków jest złe. Przykładowe idki powinny wyglądać tak: "task1", "task2" itd. Możemy to zostawić do poprawy w ramach następnego zadania. Będzie to bardziej zrozumiałe czemu nie generuje się tak id-ków.
2. Nazwa funkcji dalej jest taka sama. Powiedzmy że będziemy dodawać nowe funkcje. Wtedy też ciężko będzie je utrzymywać.
3. Inne idki też nic nie mówią. Bo np co ma mi powiedzieć li albu ul po za typem elementu z którego korzystam?

Ogólnie to zamykam te zadanie bo przechodzi moje testy akceptacyjne i dostarcza nową funkcjonalność. Nad poprawą czytelności kodu będziemy jeszcze pracować.
